version: 2

sources:
  - name: public
    tables:
      - name: telegram_medical_messages

models:
  - name: medical_source_data
    description: "This model selects all data from the telegram_medical_messages table."
    columns:
      - name: message_id
        description: "Unique identifier for each message."
        tests:
          - not_null
      - name: channel_title
        description: "Title of the Telegram channel."
      - name: channel_username
        description: "Username of the Telegram channel."
      - name: message
        description: "Content of the message."
      - name: message_date
        description: "Timestamp of the message."
      - name: emoji_used
        description: "Emojis used in the message."
      - name: youtube_links
        description: "YouTube links included in the message."

  - name: transform_medical_data
    description: "This model transforms the data by extracting product_name and usage_info from the message."
    columns:
      - name: message_id
        description: "Unique identifier for each message."
        tests:
          - not_null
      - name: channel_title
        description: "Title of the Telegram channel."
      - name: channel_username
        description: "Username of the Telegram channel."
      - name: message
        description: "Content of the message."
      - name: product_name
        description: "Extracted product name from the message."
      - name: usage_info
        description: "Extracted usage information from the message."
      - name: message_date
        description: "Timestamp of the message."
      - name: emoji_used
        description: "Emojis used in the message."
      - name: youtube_links
        description: "YouTube links included in the message."